#!/bin/sh
while read file
do
  case "$1" in
  "w") 	
    wal -i "$file"
    sed -i ~/.Xresources -re '1,1000d'
    cat ~/.cache/wal/colors.Xresources >> ~/.Xresources
    wal-telegram -t
    pywalfox update
    killall dunst && dunst &
    killall dwm
    dwmblocks &
    pkill sxiv
    notify-send "Enjoy your new colorscheme!" ;;

  "y")
    xclip -selection clipboard "$file" -t image/png &&
    notify-send "$file copied to clipboard!"
  esac
done
